
mutation AddAgent(
  $agent_id: ID!,
  $label: String!,
  $version: String!,
  $org_id: ID!,
  $tags: [String!]! = [],
  $metadata: String = ""
) {
  addAgents(
    input: {
      id: $agent_id, 
      label: $label, 
      tags: $tags, 
      _version: $version,
      metadata: $metadata,
      org: {
        connect: {
          where: {
            node: {
              id: $org_id
            }
          }
        }
      }
    }
  ) {
    agents {
      label
      createdTimestamp
    }
  }
}

