
fragment factor_skeleton_fields on Factor {
  id
  label
  tags
  _variableOrderSymbols
}

fragment factor_summary_fields on Factor {
  timestamp
  nstime
}

fragment factor_full_fields on Factor {
  fnctype
  solvable
  data
  metadata
  _version
}


mutation AddFactors(
  $id: ID!,
  $label: String!,
  $tags: [String!]!,
  $_variableOrderSymbols: [String!]!,
  $timestamp: DateTime!,
  $nstime: BigInt!,
  $fnctype: String!,
  $solvable: Int!,
  $data: String!,
  $_version: String! = "0.25",
  $fg_id: ID!,
  $variables_connect: JSON!,
  $blob_entries: JSON
) {
  addFactors(
    input: {
      id: $id,
      label: $label,
      tags: $tags,
      timestamp: $timestamp,
      nstime: $nstime,
      _variableOrderSymbols: $_variableOrderSymbols,
      fnctype: $fnctype,
      solvable: $solvable,
      data: $data,
      _version: $_version,
      fg: {
        connect: {
          where: {
            node: {id: $fg_id}
          }
        }
      }
      variables: $variables_connect
    }
  ) {
    factors {
      ...factor_skeleton_fields
      ...factor_summary_fields
      ...factor_full_fields
    }
  }
}
