mutation AddVariable(
  $id: ID!,
  $label: String!,
  $variableType: String!,
  $tags: [String!]! = ["VARIABLE"],
  $timestamp: DateTime! = "2025-01-01 00:00:00.000",
  $nstime: BigInt! = "0",
  $solvable: Int! = 1,
  $metadata: String = "e30=",
  $fg_id: ID!
) {
  addVariables(
    input: {
      id: $id, 
      label: $label, 
      variableType: $variableType, 
      tags: $tags
      solvable: $solvable,
      timestamp: $timestamp, 
      nstime: $nstime,
      metadata: $metadata, 
      _version: "0.25",
      fg: {
        connect: {
          where: {
            node: {id: $fg_id}
          }
        }
      }
    }
  ) {
    variables {
      id
    }
  }
}