mutation CreateUpload(
  $blobId: ID!, 
  $parts: Int!,
  $store_label: String!,
  $store_type: BlobStoreType!
) {
  createUpload(
    blobId: $blobId
    parts: $parts
    store: {
      label: $store_label,
      type: $store_type
    }
  ) {
    blobId
    parts {
      partNumber
      url
    }
    uploadId
  }
}
