

fragment agent_fields_summary on Agent {
  id
  label
  description
  tags
  _version
  createdTimestamp
  lastUpdatedTimestamp
}

fragment blobEntry_fields_summary on BlobEntry {
  id
  label
  size
  mimeType
  lastUpdatedTimestamp
}

fragment agent_fields_full on Agent {
  metadata
  blobEntries {
    ...blobEntry_fields_summary
  } 
  fgs {
    label
    lastUpdatedTimestamp
  }
  models {
    label
    lastUpdatedTimestamp
  }
}

query GetAgent(
  $org_id: ID!, 
  $agent_id: ID, 
  $full: Boolean = false
) {
  agents(where: {id: $agent_id}) {
    org(where: {id: $org_id}) {
      id
    } 
    ...agent_fields_summary
    ...agent_fields_full @include(if: $full)
  }
}
