
fragment blobEntry_fields on BlobEntry {
  id
  blobId
  originId
  label
  blobstore
  hash
  origin
  size
  description
  mimeType
  metadata
  timestamp
  createdTimestamp
  lastUpdatedTimestamp
  _version
  _type
}


query GetBlobEntry(
  $entry_id: ID!
) {
  blobEntries(
    where: {
      id: $entry_id
    }
  ) {
    ...blobEntry_fields
  }
}

