
fragment graph_fields_skeleton on Factorgraph {
  id
  label
  lastUpdatedTimestamp
  namespace
}

query GetGraphs(
  $org_id: ID!,
  $label_contains: String!,
) {
  factorgraphs (
    where: {label_CONTAINS: $label_contains}
  ) {
    org(
      where: {id: $org_id}
    ) {
      id
    } 
    ...graph_fields_skeleton
  }
}