mutation UpdateBlobentryMetadata(
  $id: ID!,
  $metadata: String!
) {
  updateBlobEntries(
    where: {id: $id}, 
    update: {metadata: $metadata}
  ) {
    blobEntries {
      id
      lastUpdatedTimestamp
    }
  }
}